# Generated by Django 5.2.7 on 2025-10-13 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerStore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='premission_level',
        ),
        migrations.RemoveField(
            model_name='support',
            name='premission_level',
        ),
        migrations.RemoveField(
            model_name='users',
            name='premission_level',
        ),
        migrations.AddField(
            model_name='product',
            name='permission_level',
            field=models.ForeignKey(default='manager', on_delete=django.db.models.deletion.CASCADE, related_name='product_permission_level', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='support',
            name='permission_level',
            field=models.ForeignKey(default='manager', on_delete=django.db.models.deletion.CASCADE, related_name='support_prerission_level', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='permission_level',
            field=models.CharField(choices=[('basic_user', 'Basic User'), ('premium_user', 'Premium User'), ('staff', 'Staff'), ('manager', 'Manager')], default='basic_user', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
