# Generated by Django 5.2.7 on 2025-10-14 12:45

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerStore', '0006_alter_product_user_id_alter_support_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='ComputerStore/Product_image/%Y/%m/%d', variations={'resized': {'crop': False, 'height': 480, 'width': 640}}, verbose_name='Product image'),
        ),
        migrations.AddField(
            model_name='support',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='ComputerStore/Uploaded-images/%Y/%m/%d', verbose_name='Uploaded image'),
        ),
    ]
