# Generated by Django 5.2.7 on 2025-10-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerStore', '0002_remove_product_premission_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logged_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permission_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_names',
        ),
        migrations.RemoveField(
            model_name='support',
            name='logged_in',
        ),
        migrations.RemoveField(
            model_name='support',
            name='permission_level',
        ),
        migrations.RemoveField(
            model_name='support',
            name='support_id',
        ),
        migrations.RemoveField(
            model_name='support',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='support',
            name='user_names',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='logged_in',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_names',
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
